{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "hot-reload-devtools",
    "version": "{{Hot Reload Version}}",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-devtools-{{Hot Reload Version}}.jar",
          "url": "hot-reload-devtools-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-core",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-orchestration",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-runtime-api",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-runtime-jvm",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.sellmair",
          "module": "evas",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.sellmair",
          "module": "evas-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-devtools-{{Hot Reload Version}}.jar",
          "url": "hot-reload-devtools-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hot-reload-devtools-{{Hot Reload Version}}-sources.jar",
          "url": "hot-reload-devtools-{{Hot Reload Version}}-sources.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hot-reload-devtools-{{Hot Reload Version}}-javadoc.jar",
          "url": "hot-reload-devtools-{{Hot Reload Version}}-javadoc.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    }
  ]
}
