{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "hot-reload-annotations",
    "version": "{{Hot Reload Version}}",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "{{HASH}}",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-annotations-metadata-{{Hot Reload Version}}.jar",
          "url": "hot-reload-annotations-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "{{HASH}}",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "hot-reload-annotations-kotlin-{{Hot Reload Version}}-sources.jar",
          "url": "hot-reload-annotations-{{Hot Reload Version}}-sources.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-android/{{Hot Reload Version}}/hot-reload-annotations-android-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-android",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-android/{{Hot Reload Version}}/hot-reload-annotations-android-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-android",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-android/{{Hot Reload Version}}/hot-reload-annotations-android-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-android",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iosarm64/{{Hot Reload Version}}/hot-reload-annotations-iosarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iosarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iosarm64/{{Hot Reload Version}}/hot-reload-annotations-iosarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iosarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iosarm64/{{Hot Reload Version}}/hot-reload-annotations-iosarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iosarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iossimulatorarm64/{{Hot Reload Version}}/hot-reload-annotations-iossimulatorarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iossimulatorarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iossimulatorarm64/{{Hot Reload Version}}/hot-reload-annotations-iossimulatorarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iossimulatorarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iossimulatorarm64/{{Hot Reload Version}}/hot-reload-annotations-iossimulatorarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iossimulatorarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iosx64/{{Hot Reload Version}}/hot-reload-annotations-iosx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iosx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iosx64/{{Hot Reload Version}}/hot-reload-annotations-iosx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iosx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-iosx64/{{Hot Reload Version}}/hot-reload-annotations-iosx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-iosx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-js/{{Hot Reload Version}}/hot-reload-annotations-js-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-js",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-js/{{Hot Reload Version}}/hot-reload-annotations-js-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-js",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-js/{{Hot Reload Version}}/hot-reload-annotations-js-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-js",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-jvm/{{Hot Reload Version}}/hot-reload-annotations-jvm-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-jvm",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-jvm/{{Hot Reload Version}}/hot-reload-annotations-jvm-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-jvm",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-jvm/{{Hot Reload Version}}/hot-reload-annotations-jvm-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-jvm",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-linuxarm64/{{Hot Reload Version}}/hot-reload-annotations-linuxarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-linuxarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-linuxarm64/{{Hot Reload Version}}/hot-reload-annotations-linuxarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-linuxarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-linuxx64/{{Hot Reload Version}}/hot-reload-annotations-linuxx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-linuxx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-linuxx64/{{Hot Reload Version}}/hot-reload-annotations-linuxx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-linuxx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-macosarm64/{{Hot Reload Version}}/hot-reload-annotations-macosarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-macosarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-macosarm64/{{Hot Reload Version}}/hot-reload-annotations-macosarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-macosarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-macosarm64/{{Hot Reload Version}}/hot-reload-annotations-macosarm64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-macosarm64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-macosx64/{{Hot Reload Version}}/hot-reload-annotations-macosx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-macosx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-macosx64/{{Hot Reload Version}}/hot-reload-annotations-macosx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-macosx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-macosx64/{{Hot Reload Version}}/hot-reload-annotations-macosx64-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-macosx64",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-wasm-js/{{Hot Reload Version}}/hot-reload-annotations-wasm-js-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-wasm-js",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-wasm-js/{{Hot Reload Version}}/hot-reload-annotations-wasm-js-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-wasm-js",
        "version": "{{Hot Reload Version}}"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../hot-reload-annotations-wasm-js/{{Hot Reload Version}}/hot-reload-annotations-wasm-js-{{Hot Reload Version}}.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "hot-reload-annotations-wasm-js",
        "version": "{{Hot Reload Version}}"
      }
    }
  ]
}
