{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "orchestration",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "orchestration-<HOT RELOAD VERSION>.jar",
          "url": "orchestration-<HOT RELOAD VERSION>.jar",
          "size": 73154,
          "sha512": "a4ed95a5eba72d45318a142683f66145e010d9e79d1a841b84146ce24a0b7d59f792addb9245f0ff32aff60f85dd33226190837eb1997a4fe71f797d49a49f1f",
          "sha256": "7c57d5a0dd5a696cd66048813cf131e6564becbe4f3c8ea346b6478abc8453ff",
          "sha1": "5d64ca19dacac5f5d0b34d60a90b9216dd508d37",
          "md5": "70759dd89496a4d369ea63560134cd82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "orchestration-<HOT RELOAD VERSION>.jar",
          "url": "orchestration-<HOT RELOAD VERSION>.jar",
          "size": 73154,
          "sha512": "a4ed95a5eba72d45318a142683f66145e010d9e79d1a841b84146ce24a0b7d59f792addb9245f0ff32aff60f85dd33226190837eb1997a4fe71f797d49a49f1f",
          "sha256": "7c57d5a0dd5a696cd66048813cf131e6564becbe4f3c8ea346b6478abc8453ff",
          "sha1": "5d64ca19dacac5f5d0b34d60a90b9216dd508d37",
          "md5": "70759dd89496a4d369ea63560134cd82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "orchestration-<HOT RELOAD VERSION>-sources.jar",
          "url": "orchestration-<HOT RELOAD VERSION>-sources.jar",
          "size": 11702,
          "sha512": "371cf9c6b1a7b865fe19d601517a08b496592e84103510b3f7f373890e641a516b7750dda5539a35c6681a1ef0f1eb4df79a649c696d47994e691d4622477be2",
          "sha256": "ee58662c160f1a02e55d979d94a6284652d0aedd70d5cb288e9ff563e036a7f1",
          "sha1": "9c795283d4efaf73e8d66e4a4f1438e19fe7f65a",
          "md5": "7a7a2b6527508e3e40069bcb0ef52514"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "orchestration-<HOT RELOAD VERSION>-javadoc.jar",
          "url": "orchestration-<HOT RELOAD VERSION>-javadoc.jar",
          "size": 261,
          "sha512": "18c0a64693e8aa1246bc36383d813744f03f1e0c4c8a10fa8e2c60e0c6a5e5f1b1edc921e1745d1d235d32c58ba54a93bdcc0e865c75c5aada6d61a44a2aee3c",
          "sha256": "cf5258e334cb2d7fb8d31d15c88553ce5c1c70629041c6348dee07a9f5a9fecc",
          "sha1": "822ab9a1b4b49150da37412fa57a0e8cd0611f76",
          "md5": "19b34d5e71a76a15787d5d97c09b92e3"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "orchestration",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "orchestration-<HOT RELOAD VERSION>-test-fixtures.jar",
          "url": "orchestration-<HOT RELOAD VERSION>-test-fixtures.jar",
          "size": 261,
          "sha512": "18c0a64693e8aa1246bc36383d813744f03f1e0c4c8a10fa8e2c60e0c6a5e5f1b1edc921e1745d1d235d32c58ba54a93bdcc0e865c75c5aada6d61a44a2aee3c",
          "sha256": "cf5258e334cb2d7fb8d31d15c88553ce5c1c70629041c6348dee07a9f5a9fecc",
          "sha1": "822ab9a1b4b49150da37412fa57a0e8cd0611f76",
          "md5": "19b34d5e71a76a15787d5d97c09b92e3"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "name": "hot-reload-orchestration-test-fixtures",
          "version": "<HOT RELOAD VERSION>"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "orchestration",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "orchestration-<HOT RELOAD VERSION>-test-fixtures.jar",
          "url": "orchestration-<HOT RELOAD VERSION>-test-fixtures.jar",
          "size": 261,
          "sha512": "18c0a64693e8aa1246bc36383d813744f03f1e0c4c8a10fa8e2c60e0c6a5e5f1b1edc921e1745d1d235d32c58ba54a93bdcc0e865c75c5aada6d61a44a2aee3c",
          "sha256": "cf5258e334cb2d7fb8d31d15c88553ce5c1c70629041c6348dee07a9f5a9fecc",
          "sha1": "822ab9a1b4b49150da37412fa57a0e8cd0611f76",
          "md5": "19b34d5e71a76a15787d5d97c09b92e3"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "name": "hot-reload-orchestration-test-fixtures",
          "version": "<HOT RELOAD VERSION>"
        }
      ]
    }
  ]
}
