{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "test-core",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-core-<HOT RELOAD VERSION>.jar",
          "url": "test-core-<HOT RELOAD VERSION>.jar",
          "size": 6050,
          "sha512": "ef347a05a4f7ddd86be1c5b0f1ed507150ffc0b0e22eaee0d1a18c5cb1c727d783efdea461e62214016225e7b6e55f4329dd55fb9e51917b2e49c1bf0776ff1b",
          "sha256": "227714428d597dafce2e6b6d73f21a48187150b9257e5a0245b6afe2c8542f24",
          "sha1": "ebdebd110421afb02702f273ffd8e1cf13829058",
          "md5": "55f37373b3147be98aff4078e3680809"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-core-<HOT RELOAD VERSION>.jar",
          "url": "test-core-<HOT RELOAD VERSION>.jar",
          "size": 6050,
          "sha512": "ef347a05a4f7ddd86be1c5b0f1ed507150ffc0b0e22eaee0d1a18c5cb1c727d783efdea461e62214016225e7b6e55f4329dd55fb9e51917b2e49c1bf0776ff1b",
          "sha256": "227714428d597dafce2e6b6d73f21a48187150b9257e5a0245b6afe2c8542f24",
          "sha1": "ebdebd110421afb02702f273ffd8e1cf13829058",
          "md5": "55f37373b3147be98aff4078e3680809"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-core-<HOT RELOAD VERSION>-sources.jar",
          "url": "test-core-<HOT RELOAD VERSION>-sources.jar",
          "size": 1972,
          "sha512": "480bd1c0d70f69db6999911094c9500680902f7320c75ec1b23a57fb648ae559a47e002a950aa20b46b0cdc37a152d968248f6d28c7e9b409c08f5fd875aa445",
          "sha256": "552e3924dfd1cd36d275b3597d1b62c7b7d271ec6017473762b61513326bcb3a",
          "sha1": "35a36426f7588e0999824381f0090282f7cf8223",
          "md5": "06fa803a28fe1ce6da39a4e9c6c5d1a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-core-<HOT RELOAD VERSION>-javadoc.jar",
          "url": "test-core-<HOT RELOAD VERSION>-javadoc.jar",
          "size": 261,
          "sha512": "18c0a64693e8aa1246bc36383d813744f03f1e0c4c8a10fa8e2c60e0c6a5e5f1b1edc921e1745d1d235d32c58ba54a93bdcc0e865c75c5aada6d61a44a2aee3c",
          "sha256": "cf5258e334cb2d7fb8d31d15c88553ce5c1c70629041c6348dee07a9f5a9fecc",
          "sha1": "822ab9a1b4b49150da37412fa57a0e8cd0611f76",
          "md5": "19b34d5e71a76a15787d5d97c09b92e3"
        }
      ]
    }
  ]
}
