{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "runtime-api",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-metadata-<HOT RELOAD VERSION>.jar",
          "url": "runtime-api-<HOT RELOAD VERSION>.jar",
          "size": 5193,
          "sha512": "61c90fd1c3a3c999417c5fcf56158f6048d3e85e448b2b3886f324eacbdb8fdc2e83df3347f79c2595c382e60e77fd3e314b1ea3405c96434d95f8d7e568832c",
          "sha256": "8800e13ae38627e0dc994994db674760b5276bd8f5ef8f32dd5bf3e38e98fd6f",
          "sha1": "359e48b0d0268450c7812372aad19f7558871ab4",
          "md5": "021efc301a684d0c03ea2c5373a90d0f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "hot-reload-runtime-api-kotlin-<HOT RELOAD VERSION>-sources.jar",
          "url": "runtime-api-<HOT RELOAD VERSION>-sources.jar",
          "size": 3916,
          "sha512": "466409993b63860de279beed924b990ce792019a7580c27d9ae95a97be29fbc320688d25a16a19be579c0cfcacadf0c7dfb811bcdbf5cabda09911fb6a4b1de7",
          "sha256": "98e36377544037036a4361f7a03dd339b3d4c1d699b853a52663f98bf8d579a3",
          "sha1": "351c17ef76983f924841c70a3629607fcaf67376",
          "md5": "105db3c5f4edfbaf71c005b797c1a97d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android/<HOT RELOAD VERSION>/runtime-api-android-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-android",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android/<HOT RELOAD VERSION>/runtime-api-android-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-android",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-api-android/<HOT RELOAD VERSION>/runtime-api-android-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-android",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosarm64/<HOT RELOAD VERSION>/runtime-api-iosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosarm64/<HOT RELOAD VERSION>/runtime-api-iosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosarm64/<HOT RELOAD VERSION>/runtime-api-iosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosarm64/<HOT RELOAD VERSION>/runtime-api-iosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iossimulatorarm64/<HOT RELOAD VERSION>/runtime-api-iossimulatorarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iossimulatorarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iossimulatorarm64/<HOT RELOAD VERSION>/runtime-api-iossimulatorarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iossimulatorarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iossimulatorarm64/<HOT RELOAD VERSION>/runtime-api-iossimulatorarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iossimulatorarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iossimulatorarm64/<HOT RELOAD VERSION>/runtime-api-iossimulatorarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iossimulatorarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosx64/<HOT RELOAD VERSION>/runtime-api-iosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosx64/<HOT RELOAD VERSION>/runtime-api-iosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosx64/<HOT RELOAD VERSION>/runtime-api-iosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-iosx64/<HOT RELOAD VERSION>/runtime-api-iosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-iosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../runtime-api-js/<HOT RELOAD VERSION>/runtime-api-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../runtime-api-js/<HOT RELOAD VERSION>/runtime-api-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../runtime-api-js/<HOT RELOAD VERSION>/runtime-api-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../runtime-api-js/<HOT RELOAD VERSION>/runtime-api-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-api-jvm/<HOT RELOAD VERSION>/runtime-api-jvm-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-jvm",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-api-jvm/<HOT RELOAD VERSION>/runtime-api-jvm-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-jvm",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-api-jvm/<HOT RELOAD VERSION>/runtime-api-jvm-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-jvm",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-linuxarm64/<HOT RELOAD VERSION>/runtime-api-linuxarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-linuxarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-linuxarm64/<HOT RELOAD VERSION>/runtime-api-linuxarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-linuxarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "linuxArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-linuxarm64/<HOT RELOAD VERSION>/runtime-api-linuxarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-linuxarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-linuxx64/<HOT RELOAD VERSION>/runtime-api-linuxx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-linuxx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-linuxx64/<HOT RELOAD VERSION>/runtime-api-linuxx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-linuxx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "linuxX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-linuxx64/<HOT RELOAD VERSION>/runtime-api-linuxx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-linuxx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosarm64/<HOT RELOAD VERSION>/runtime-api-macosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosarm64/<HOT RELOAD VERSION>/runtime-api-macosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosarm64/<HOT RELOAD VERSION>/runtime-api-macosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosarm64/<HOT RELOAD VERSION>/runtime-api-macosarm64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosarm64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosx64/<HOT RELOAD VERSION>/runtime-api-macosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosx64/<HOT RELOAD VERSION>/runtime-api-macosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosx64/<HOT RELOAD VERSION>/runtime-api-macosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-api-macosx64/<HOT RELOAD VERSION>/runtime-api-macosx64-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-macosx64",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-api-wasm-js/<HOT RELOAD VERSION>/runtime-api-wasm-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-wasm-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-api-wasm-js/<HOT RELOAD VERSION>/runtime-api-wasm-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-wasm-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-api-wasm-js/<HOT RELOAD VERSION>/runtime-api-wasm-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-wasm-js",
        "version": "<HOT RELOAD VERSION>"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../runtime-api-wasm-js/<HOT RELOAD VERSION>/runtime-api-wasm-js-<HOT RELOAD VERSION>.module",
        "group": "org.jetbrains.compose.hot-reload",
        "module": "runtime-api-wasm-js",
        "version": "<HOT RELOAD VERSION>"
      }
    }
  ]
}
