{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "gradle-core",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-core-<HOT RELOAD VERSION>.jar",
          "url": "gradle-core-<HOT RELOAD VERSION>.jar",
          "size": 20644,
          "sha512": "65a7b24c749a6aacb72bcc91a522d4fd2e5b596794ceb6442dc5b5ed21e766c55eefd7c92c780fa75b112b4a57de7f3901ee1079f7a138b2b416c519ac563dd3",
          "sha256": "5e07811bc3397e8a6f728c86cf3185c170cb96c25f7355d603e5d8621ace4f2c",
          "sha1": "dc7f828e308d40853fe351e43d7ecea12e900caf",
          "md5": "1150b5ff92c4ff66294686aac872b275"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-core-<HOT RELOAD VERSION>.jar",
          "url": "gradle-core-<HOT RELOAD VERSION>.jar",
          "size": 20644,
          "sha512": "65a7b24c749a6aacb72bcc91a522d4fd2e5b596794ceb6442dc5b5ed21e766c55eefd7c92c780fa75b112b4a57de7f3901ee1079f7a138b2b416c519ac563dd3",
          "sha256": "5e07811bc3397e8a6f728c86cf3185c170cb96c25f7355d603e5d8621ace4f2c",
          "sha1": "dc7f828e308d40853fe351e43d7ecea12e900caf",
          "md5": "1150b5ff92c4ff66294686aac872b275"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-core-<HOT RELOAD VERSION>-sources.jar",
          "url": "gradle-core-<HOT RELOAD VERSION>-sources.jar",
          "size": 6796,
          "sha512": "664e16a60464f87670e4424ad04839d29893d8201d46109a85dc60902c89b54f76633d526007c873ad51ff4b449b5e539d05edce4219d3847f30b87908c8e8b1",
          "sha256": "64a5a64a7d7d0496222b2d08bf604b1926dcfe5520fade38cc334b73f3013e50",
          "sha1": "359c02f2d28fee993f62d19b946aaf28cef53483",
          "md5": "38c2e3ac3a70454d8a9c02377131939d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-core-<HOT RELOAD VERSION>-javadoc.jar",
          "url": "gradle-core-<HOT RELOAD VERSION>-javadoc.jar",
          "size": 261,
          "sha512": "18c0a64693e8aa1246bc36383d813744f03f1e0c4c8a10fa8e2c60e0c6a5e5f1b1edc921e1745d1d235d32c58ba54a93bdcc0e865c75c5aada6d61a44a2aee3c",
          "sha256": "cf5258e334cb2d7fb8d31d15c88553ce5c1c70629041c6348dee07a9f5a9fecc",
          "sha1": "822ab9a1b4b49150da37412fa57a0e8cd0611f76",
          "md5": "19b34d5e71a76a15787d5d97c09b92e3"
        }
      ]
    }
  ]
}
