@file:Suppress("UnstableApiUsage")

/*
* Copyright 2024-2025 JetBrains s.r.o. and Compose Hot Reload contributors.
* Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
*/

/*
Template settings.gradle.kts:
The actual test will not use this, but replace it with the version generated by the test.
 */

pluginManagement {
    repositories {
        maven(file("../../../../../../build/repo"))
        mavenCentral()
        google()
    }

    plugins {
        kotlin("jvm") version "2.2.21"
        kotlin("plugin.compose") version "2.2.21"
        id("org.jetbrains.compose") version "1.9.0"
        id("org.jetbrains.compose.hot-reload") version "1.1.0-alpha+176"
    }
}

dependencyResolutionManagement {
    repositories {
        maven(file("../../../../../../build/repo"))
        mavenCentral()
        google()
    }
}
