{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/<HOT RELOAD VERSION>/runtime-api-<HOT RELOAD VERSION>.module",
    "group": "org.jetbrains.compose.hot-reload",
    "module": "runtime-api",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-macosArm64Main-<HOT RELOAD VERSION>.klib",
          "url": "runtime-api-macosarm64-<HOT RELOAD VERSION>.klib",
          "size": 11441,
          "sha512": "dcfd12dc5d603a4f1fcb927926e8de99a9304195298b8f586bf8ca9c8c2c9c48852d1b10492e10c6186017924a2845fc8651843aca5b9a3e426bc58b92f88e40",
          "sha256": "8cc905abc6c89e8d59454a7206ad96affc1435f50ed19a2ffa25e4d6498591ed",
          "sha1": "119082d59374fb2c3e60b4539bdf3b52df80834f",
          "md5": "073db48095ec8f2baae681f473b2c4a8"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "hot-reload-runtime-api-macosarm64-<HOT RELOAD VERSION>-sources.jar",
          "url": "runtime-api-macosarm64-<HOT RELOAD VERSION>-sources.jar",
          "size": 3916,
          "sha512": "a2ddf4d578d43a3a717df87a59b592f332b478147d91aab3b359c7c9dd9145c638b2c12a95da1ad0f62c284c55b22542d071d85259e77d5dd809de7b2e61a6b3",
          "sha256": "52af30a820561a5b87d5f2a336ddc750c562612d88c8b6c4d6846ee85eee7bc9",
          "sha1": "4f657750522741b1a7aae5227bb1ff9240cadc0d",
          "md5": "44c1cee2639c38bf9a209dc86c9211a1"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-<HOT RELOAD VERSION>.kotlin_resources.zip",
          "url": "runtime-api-macosarm64-<HOT RELOAD VERSION>-kotlin_resources.kotlin_resources.zip",
          "size": 398,
          "sha512": "407084270e0436508c4b3959f9b027da0a9b61464be417b86463e5c11de62b5b2eda28ac5e5285bdba01e75565eeead7ab0fd7671984b76e3935fb24c99f0ce9",
          "sha256": "60bb1902eeb4f7050fe3526406c9632b9678c5048b8a9907feb3a3253aefafd5",
          "sha1": "864110dce1f831ed8e8704cef40894bd525fb685",
          "md5": "6c6cb831eaf3ff278edf3b6f92d11272"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-macosarm64-<HOT RELOAD VERSION>-metadata.jar",
          "url": "runtime-api-macosarm64-<HOT RELOAD VERSION>-metadata.jar",
          "size": 261,
          "sha512": "c4dd693e23f651fe4521dd7a42025a671dda0c9767ba0c60835835886a0f7d7539a8b5340ec37b050827b85ca44ad76b371bb0f936c9f40d1f7e9597a83570d1",
          "sha256": "3c9371a168d1393b0d7e117ce4a6e0ac63f7d9d9b5a9edfae843c4a82d6e5bc6",
          "sha1": "31afb1eef219b64481c3512695e8588f4abe4172",
          "md5": "1bc9db44f31cca4747ae1aaae3bf6f7e"
        }
      ]
    }
  ]
}
