{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/<HOT RELOAD VERSION>/runtime-api-<HOT RELOAD VERSION>.module",
    "group": "org.jetbrains.compose.hot-reload",
    "module": "runtime-api",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-wasm-js-<HOT RELOAD VERSION>.klib",
          "url": "runtime-api-wasm-js-<HOT RELOAD VERSION>.klib",
          "size": 11264,
          "sha512": "e5de7b9660e6e184be058bf8d6956e9a674d9abd5d1bfda61a22543055a4e7b1e32132b9f2007ad632176df86e406f55f79494c27c74909d3ae8e18e63dbb3c0",
          "sha256": "6bd5eb4d94426b2dc5ad37d6956911cc46b4447133c8a05783482e795c25059f",
          "sha1": "489335102316cb82d5a432ac8a34cf7dcf89adf6",
          "md5": "4e6480499873d8eacea82f601b6ae93d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-wasm-js-<HOT RELOAD VERSION>.klib",
          "url": "runtime-api-wasm-js-<HOT RELOAD VERSION>.klib",
          "size": 11264,
          "sha512": "e5de7b9660e6e184be058bf8d6956e9a674d9abd5d1bfda61a22543055a4e7b1e32132b9f2007ad632176df86e406f55f79494c27c74909d3ae8e18e63dbb3c0",
          "sha256": "6bd5eb4d94426b2dc5ad37d6956911cc46b4447133c8a05783482e795c25059f",
          "sha1": "489335102316cb82d5a432ac8a34cf7dcf89adf6",
          "md5": "4e6480499873d8eacea82f601b6ae93d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "hot-reload-runtime-api-wasm-js-<HOT RELOAD VERSION>-sources.jar",
          "url": "runtime-api-wasm-js-<HOT RELOAD VERSION>-sources.jar",
          "size": 3916,
          "sha512": "a2ddf4d578d43a3a717df87a59b592f332b478147d91aab3b359c7c9dd9145c638b2c12a95da1ad0f62c284c55b22542d071d85259e77d5dd809de7b2e61a6b3",
          "sha256": "52af30a820561a5b87d5f2a336ddc750c562612d88c8b6c4d6846ee85eee7bc9",
          "sha1": "4f657750522741b1a7aae5227bb1ff9240cadc0d",
          "md5": "44c1cee2639c38bf9a209dc86c9211a1"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-<HOT RELOAD VERSION>.kotlin_resources.zip",
          "url": "runtime-api-wasm-js-<HOT RELOAD VERSION>-kotlin_resources.kotlin_resources.zip",
          "size": 398,
          "sha512": "407084270e0436508c4b3959f9b027da0a9b61464be417b86463e5c11de62b5b2eda28ac5e5285bdba01e75565eeead7ab0fd7671984b76e3935fb24c99f0ce9",
          "sha256": "60bb1902eeb4f7050fe3526406c9632b9678c5048b8a9907feb3a3253aefafd5",
          "sha1": "864110dce1f831ed8e8704cef40894bd525fb685",
          "md5": "6c6cb831eaf3ff278edf3b6f92d11272"
        }
      ]
    }
  ]
}
