{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "analysis",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "analysis-<HOT RELOAD VERSION>.jar",
          "url": "analysis-<HOT RELOAD VERSION>.jar",
          "size": 159844,
          "sha512": "0e63520b3541850ef293066ce8de1adfdb415914e88b6bf34a8599854d5909e61b483ac716e34e90fa6bb61e6ec99e4782426f701aaf7e402feb90ca54beab80",
          "sha256": "9e017be2ba5ded175cb4b63c18e838d9593321d17cb31238d6e500b48a7831b0",
          "sha1": "58434286cf2bb60cc4a87188743c4d886cc3ca24",
          "md5": "06d7c1ee45017d383d5c283d1cd60ec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "analysis-<HOT RELOAD VERSION>.jar",
          "url": "analysis-<HOT RELOAD VERSION>.jar",
          "size": 159844,
          "sha512": "0e63520b3541850ef293066ce8de1adfdb415914e88b6bf34a8599854d5909e61b483ac716e34e90fa6bb61e6ec99e4782426f701aaf7e402feb90ca54beab80",
          "sha256": "9e017be2ba5ded175cb4b63c18e838d9593321d17cb31238d6e500b48a7831b0",
          "sha1": "58434286cf2bb60cc4a87188743c4d886cc3ca24",
          "md5": "06d7c1ee45017d383d5c283d1cd60ec8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analysis-<HOT RELOAD VERSION>-sources.jar",
          "url": "analysis-<HOT RELOAD VERSION>-sources.jar",
          "size": 22657,
          "sha512": "dcc56269af022f7c85ed75212e3f890471494415429b398a342338fe7df79fd6d93e78c4a0b1b1dd5c5e41e842c785baf5667fae09a67bf61ef46652342705d0",
          "sha256": "2d75af13510ab9996a6be44933b511719366685d5d51b0f704d70bd4fb25f1d9",
          "sha1": "ca80f8260b46279c9e784c617775a6d2665aa4f3",
          "md5": "e2f64edf3906399d59a22ca43926ffa4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analysis-<HOT RELOAD VERSION>-javadoc.jar",
          "url": "analysis-<HOT RELOAD VERSION>-javadoc.jar",
          "size": 261,
          "sha512": "18c0a64693e8aa1246bc36383d813744f03f1e0c4c8a10fa8e2c60e0c6a5e5f1b1edc921e1745d1d235d32c58ba54a93bdcc0e865c75c5aada6d61a44a2aee3c",
          "sha256": "cf5258e334cb2d7fb8d31d15c88553ce5c1c70629041c6348dee07a9f5a9fecc",
          "sha1": "822ab9a1b4b49150da37412fa57a0e8cd0611f76",
          "md5": "19b34d5e71a76a15787d5d97c09b92e3"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "analysis",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "analysis-<HOT RELOAD VERSION>-test-fixtures.jar",
          "url": "analysis-<HOT RELOAD VERSION>-test-fixtures.jar",
          "size": 6289,
          "sha512": "a4fdfddf014c832682a3ceb948a914a7ca266105816e786691ec200346095c23ad0d9eabce00875dd4f514f6ebae89bb31bcc604e6df08dbe3b23dcf041d70ef",
          "sha256": "90ace275e8ce18947020465f0dc66bd251195389956f2a02e451f6b5ede82be4",
          "sha1": "8f664acfd5c9eb42667bfc6d0e48a772702c7db8",
          "md5": "a0530e8a41e32d82bc070ffc7883505c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "name": "hot-reload-analysis-test-fixtures",
          "version": "<HOT RELOAD VERSION>"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "analysis",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "analysis-<HOT RELOAD VERSION>-test-fixtures.jar",
          "url": "analysis-<HOT RELOAD VERSION>-test-fixtures.jar",
          "size": 6289,
          "sha512": "a4fdfddf014c832682a3ceb948a914a7ca266105816e786691ec200346095c23ad0d9eabce00875dd4f514f6ebae89bb31bcc604e6df08dbe3b23dcf041d70ef",
          "sha256": "90ace275e8ce18947020465f0dc66bd251195389956f2a02e451f6b5ede82be4",
          "sha1": "8f664acfd5c9eb42667bfc6d0e48a772702c7db8",
          "md5": "a0530e8a41e32d82bc070ffc7883505c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "name": "hot-reload-analysis-test-fixtures",
          "version": "<HOT RELOAD VERSION>"
        }
      ]
    }
  ]
}
