{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/<HOT RELOAD VERSION>/runtime-api-<HOT RELOAD VERSION>.module",
    "group": "org.jetbrains.compose.hot-reload",
    "module": "runtime-api",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-linuxX64Main-<HOT RELOAD VERSION>.klib",
          "url": "runtime-api-linuxx64-<HOT RELOAD VERSION>.klib",
          "size": 11424,
          "sha512": "29a8f4dbdcc557504c4409611d32c99da279653e6e1f94ad5b7ea8dea380a4f6657c8142295514affbcc7bc363647b3c2ef56517195336bafc3d06df5d7a78b0",
          "sha256": "38c9309b47d49600d8e6f2707f908e6c179e82a6e0abba94d44ccaf650fc31aa",
          "sha1": "c73e8f44035af581a23f9258cdf6a34b0147e359",
          "md5": "9f2cce2afe885824a4491fdf901b6844"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "hot-reload-runtime-api-linuxx64-<HOT RELOAD VERSION>-sources.jar",
          "url": "runtime-api-linuxx64-<HOT RELOAD VERSION>-sources.jar",
          "size": 3916,
          "sha512": "466409993b63860de279beed924b990ce792019a7580c27d9ae95a97be29fbc320688d25a16a19be579c0cfcacadf0c7dfb811bcdbf5cabda09911fb6a4b1de7",
          "sha256": "98e36377544037036a4361f7a03dd339b3d4c1d699b853a52663f98bf8d579a3",
          "sha1": "351c17ef76983f924841c70a3629607fcaf67376",
          "md5": "105db3c5f4edfbaf71c005b797c1a97d"
        }
      ]
    },
    {
      "name": "linuxX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-<HOT RELOAD VERSION>.kotlin_resources.zip",
          "url": "runtime-api-linuxx64-<HOT RELOAD VERSION>-kotlin_resources.kotlin_resources.zip",
          "size": 398,
          "sha512": "407084270e0436508c4b3959f9b027da0a9b61464be417b86463e5c11de62b5b2eda28ac5e5285bdba01e75565eeead7ab0fd7671984b76e3935fb24c99f0ce9",
          "sha256": "60bb1902eeb4f7050fe3526406c9632b9678c5048b8a9907feb3a3253aefafd5",
          "sha1": "864110dce1f831ed8e8704cef40894bd525fb685",
          "md5": "6c6cb831eaf3ff278edf3b6f92d11272"
        }
      ]
    }
  ]
}
