{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/<HOT RELOAD VERSION>/runtime-api-<HOT RELOAD VERSION>.module",
    "group": "org.jetbrains.compose.hot-reload",
    "module": "runtime-api",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-js-<HOT RELOAD VERSION>.klib",
          "url": "runtime-api-js-<HOT RELOAD VERSION>.klib",
          "size": 11271,
          "sha512": "546d7bcb45c6891d3e07340c5a98a19397846d89e6b2bccd457f48516a522c6b48f3fc6176288568157cdef2aedfc8758f081b01f9263b6aa973350b3a092a54",
          "sha256": "2fe329072eecebc50f61bf79006ebe2efe98b818145a0691b599b04d24b98edc",
          "sha1": "034394a79c4ddfefa799d0f28f8e1eb46a0beffc",
          "md5": "dd2e3d0e3f46e8117b8f17391121deb3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-js-<HOT RELOAD VERSION>.klib",
          "url": "runtime-api-js-<HOT RELOAD VERSION>.klib",
          "size": 11271,
          "sha512": "546d7bcb45c6891d3e07340c5a98a19397846d89e6b2bccd457f48516a522c6b48f3fc6176288568157cdef2aedfc8758f081b01f9263b6aa973350b3a092a54",
          "sha256": "2fe329072eecebc50f61bf79006ebe2efe98b818145a0691b599b04d24b98edc",
          "sha1": "034394a79c4ddfefa799d0f28f8e1eb46a0beffc",
          "md5": "dd2e3d0e3f46e8117b8f17391121deb3"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "hot-reload-runtime-api-js-<HOT RELOAD VERSION>-sources.jar",
          "url": "runtime-api-js-<HOT RELOAD VERSION>-sources.jar",
          "size": 3916,
          "sha512": "a2ddf4d578d43a3a717df87a59b592f332b478147d91aab3b359c7c9dd9145c638b2c12a95da1ad0f62c284c55b22542d071d85259e77d5dd809de7b2e61a6b3",
          "sha256": "52af30a820561a5b87d5f2a336ddc750c562612d88c8b6c4d6846ee85eee7bc9",
          "sha1": "4f657750522741b1a7aae5227bb1ff9240cadc0d",
          "md5": "44c1cee2639c38bf9a209dc86c9211a1"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-<HOT RELOAD VERSION>.kotlin_resources.zip",
          "url": "runtime-api-js-<HOT RELOAD VERSION>-kotlin_resources.kotlin_resources.zip",
          "size": 398,
          "sha512": "407084270e0436508c4b3959f9b027da0a9b61464be417b86463e5c11de62b5b2eda28ac5e5285bdba01e75565eeead7ab0fd7671984b76e3935fb24c99f0ce9",
          "sha256": "60bb1902eeb4f7050fe3526406c9632b9678c5048b8a9907feb3a3253aefafd5",
          "sha1": "864110dce1f831ed8e8704cef40894bd525fb685",
          "md5": "6c6cb831eaf3ff278edf3b6f92d11272"
        }
      ]
    }
  ]
}
