{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-api/<HOT RELOAD VERSION>/runtime-api-<HOT RELOAD VERSION>.module",
    "group": "org.jetbrains.compose.hot-reload",
    "module": "runtime-api",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-jvm-<HOT RELOAD VERSION>.jar",
          "url": "runtime-api-jvm-<HOT RELOAD VERSION>.jar",
          "size": 13228,
          "sha512": "f9f6aa2481520e15c39e83e577c2a8dca8a4d80fee071de6a5a4f53dcb447fd7d441bd7dfd7f416a677380276a6631ebbee042b709461a10925edf32d7fb9014",
          "sha256": "fb6a7b3cc599342f2b500a6a435eccf2fb9ed41da972c7d4802cdb4a7e031462",
          "sha1": "442228d88b19fcdfe131f6bd83d4b23c0d662f64",
          "md5": "7aa4badf1332f05476360b39d33ff3b7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "runtime-jvm",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-runtime-api-jvm-<HOT RELOAD VERSION>.jar",
          "url": "runtime-api-jvm-<HOT RELOAD VERSION>.jar",
          "size": 13228,
          "sha512": "f9f6aa2481520e15c39e83e577c2a8dca8a4d80fee071de6a5a4f53dcb447fd7d441bd7dfd7f416a677380276a6631ebbee042b709461a10925edf32d7fb9014",
          "sha256": "fb6a7b3cc599342f2b500a6a435eccf2fb9ed41da972c7d4802cdb4a7e031462",
          "sha1": "442228d88b19fcdfe131f6bd83d4b23c0d662f64",
          "md5": "7aa4badf1332f05476360b39d33ff3b7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "hot-reload-runtime-api-jvm-<HOT RELOAD VERSION>-sources.jar",
          "url": "runtime-api-jvm-<HOT RELOAD VERSION>-sources.jar",
          "size": 4633,
          "sha512": "9acd8acb2124bafa9d65113bbc1d2ca9e1867bd0a98f06f9d79d47d64adc10416c1036d1d7a9fc433bda2ac96430f0342e3cb62542a99177bd543fcd00364add",
          "sha256": "7d004cc115071e61f2479f01dc4dc9f6c3b9121853a7a362cd3c7a7ada656524",
          "sha1": "77c7ef54bfc5da1326c55a79fffd240412dd500e",
          "md5": "9a28299031e86c01d577b1577b0d9011"
        }
      ]
    }
  ]
}
