{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "hot-reload-agent",
    "version": "{{Hot Reload Version}}",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-agent-{{Hot Reload Version}}.jar",
          "url": "hot-reload-agent-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-core",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-orchestration",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-analysis",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-agent-{{Hot Reload Version}}.jar",
          "url": "hot-reload-agent-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hot-reload-agent-{{Hot Reload Version}}-sources.jar",
          "url": "hot-reload-agent-{{Hot Reload Version}}-sources.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hot-reload-agent-{{Hot Reload Version}}-javadoc.jar",
          "url": "hot-reload-agent-{{Hot Reload Version}}-javadoc.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "{{HASH}}",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "hot-reload-agent-{{Hot Reload Version}}-standalone.jar",
          "url": "hot-reload-agent-{{Hot Reload Version}}-standalone.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    }
  ]
}
