{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "hot-reload-analysis",
    "version": "{{Hot Reload Version}}",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-analysis-{{Hot Reload Version}}.jar",
          "url": "hot-reload-analysis-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-core",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-analysis-{{Hot Reload Version}}.jar",
          "url": "hot-reload-analysis-{{Hot Reload Version}}.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hot-reload-analysis-{{Hot Reload Version}}-sources.jar",
          "url": "hot-reload-analysis-{{Hot Reload Version}}-sources.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hot-reload-analysis-{{Hot Reload Version}}-javadoc.jar",
          "url": "hot-reload-analysis-{{Hot Reload Version}}-javadoc.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ]
    },
    {
      "name": "{{HASH}}",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-analysis",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-analysis-{{Hot Reload Version}}-test-fixtures.jar",
          "url": "hot-reload-analysis-{{Hot Reload Version}}-test-fixtures.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "name": "hot-reload-analysis-test-fixtures",
          "version": "{{Hot Reload Version}}"
        }
      ]
    },
    {
      "name": "{{HASH}}",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-core",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-core",
          "version": {
            "requires": "{{Hot Reload Version}}"
          },
          "{{HASH}}": [
            {
              "group": "org.jetbrains.compose.hot-reload",
              "name": "hot-reload-core-test-fixtures"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "hot-reload-analysis",
          "version": {
            "requires": "{{Hot Reload Version}}"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "{{HASH}}": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hot-reload-analysis-{{Hot Reload Version}}-test-fixtures.jar",
          "url": "hot-reload-analysis-{{Hot Reload Version}}-test-fixtures.jar",
          "size": {{SIZE}},
          "sha512": "{{HASH}}",
          "sha256": "{{HASH}}",
          "sha1": "{{HASH}}",
          "md5": "{{HASH}}"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "name": "hot-reload-analysis-test-fixtures",
          "version": "{{Hot Reload Version}}"
        }
      ]
    }
  ]
}
