{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.hot-reload",
    "module": "test-gradle",
    "version": "<HOT RELOAD VERSION>",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-gradle-<HOT RELOAD VERSION>.jar",
          "url": "test-gradle-<HOT RELOAD VERSION>.jar",
          "size": 504685,
          "sha512": "5929e89a49545583f99408fc41821972576bdf0c07e52803bbc2a9ac64937f949784dd4c27902499fb93f4239bca308652dea6892637e121793dfd71aa99556d",
          "sha256": "6efc21a39df779c925485fc50f649f8d20c1150b41da1b89d46b07d00547cec7",
          "sha1": "899ba4282f454e84b3734e582beff26a9d9d134b",
          "md5": "9c298276604a2d78d1344818a5974e9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "test-core",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.compose.hot-reload",
          "module": "orchestration",
          "version": {
            "requires": "<HOT RELOAD VERSION>"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "test-gradle-<HOT RELOAD VERSION>.jar",
          "url": "test-gradle-<HOT RELOAD VERSION>.jar",
          "size": 504685,
          "sha512": "5929e89a49545583f99408fc41821972576bdf0c07e52803bbc2a9ac64937f949784dd4c27902499fb93f4239bca308652dea6892637e121793dfd71aa99556d",
          "sha256": "6efc21a39df779c925485fc50f649f8d20c1150b41da1b89d46b07d00547cec7",
          "sha1": "899ba4282f454e84b3734e582beff26a9d9d134b",
          "md5": "9c298276604a2d78d1344818a5974e9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-gradle-<HOT RELOAD VERSION>-sources.jar",
          "url": "test-gradle-<HOT RELOAD VERSION>-sources.jar",
          "size": 32146,
          "sha512": "ca41ee11e5f7df3c47d514401760d63b830d56bbe2c6c8530dada5ed7386379a67403d28fef99bf052851450a486ce3701e0aeb374189d92289fb1ad0abb6be4",
          "sha256": "45ab086a25333e5e78f07c0dada339d650d5fb154beed7b11e0c43420076d1e1",
          "sha1": "711c0c32686e471d1651fdddb4d61097059e9ce9",
          "md5": "8fd3a00f9d52c8b610faad5e8283cdbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-gradle-<HOT RELOAD VERSION>-javadoc.jar",
          "url": "test-gradle-<HOT RELOAD VERSION>-javadoc.jar",
          "size": 261,
          "sha512": "5c492b89219935bf1aaf13a60f882a30b9f4df72e8cfaf96d128d0372ef76237925f5a3419eca64bfc377b5e10735ec558462cede1083870336393b7eb17297d",
          "sha256": "d3952d51c058c25906a4f33185d13a04753c23077163d64e56e6a85b1c3682fa",
          "sha1": "ef3745d59453f912d03e029e8b478eadf23cfa19",
          "md5": "4ba4d712823c2afd2a722aacc0aca39e"
        }
      ]
    }
  ]
}
